apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/charibnb/reservations/prod
          name: reservations
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: PORT
              value: "8004"
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: "8002"
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: "8001"
          ports:
            - containerPort: 8004
