apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  ports:
    - name: "http"
      port: 8004
      protocol: TCP
      targetPort: 8004
      nodePort: 30541
  selector:
    app: reservations
  type: NodePort
