apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments
spec:
  ports:
    - name: "tcp"
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: payments
  type: ClusterIP
