version: '3'

services:
  reservations-microservice:
    build:
      context: ./
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn start:dev reservations
    env_file:
      - ./apps/reservations/.env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
  auth-microservice:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
  payments-microservice:
    build:
      context: ./
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn start:dev payments
    env_file:
      - ./apps/payments/.env
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1