version: '3'

services:
  reservations-microservice:
    build:
      context: ./
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm start:dev reservations
    env_file:
      - ./apps/reservations/.env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - rabbitmq
  auth-microservice:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    env_file:
      - ./apps/auth/.env
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - rabbitmq
  payments-microservice:
    build:
      context: ./
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:dev payments
    env_file:
      - ./apps/payments/.env
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - rabbitmq
  notifications-microservice:
    build:
      context: ./
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm start:dev notifications
    env_file:
      - ./apps/notifications/.env
    restart: always
    ports:
      - "8004:8004"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - rabbitmq
  gateway:
    build:
      context: ./
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm start:dev gateway
    env_file:
      - ./apps/gateway/.env
    restart: always
    ports:
      - "8005:8005"
    volumes:
      - .:/usr/src/app
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"