apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
    - name: "tcp"
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: notifications
  type: ClusterIP
