apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-tcp
spec:
  ports:
    - name: "tcp"
      port: 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: auth
  type: ClusterIP
