apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-http
spec:
  ports:
    - name: "http"
      port: 8003
      protocol: TCP
      targetPort: 8003
      nodePort: 30542
  selector:
    app: auth
  type: NodePort
